import Head from "next/head";
import { useRouter } from "next/router";
import { Fragment } from "react";

import EventList from "../../components/events/EventList";
import ResultsTitle from "../../components/events/ResultsTitle";
import Button from "../../components/ui/Button";
import ErrorAlert from "../../components/ui/ErrorAlert";
import { getFilteredEvents } from "../../utils/dummy-data";

const FilteredEventsPage = () => {
  const router = useRouter();
  const params = router.query.slug;
  if (!params) return <p className="center">Loading...</p>;

  const year = params[0];
  const month = params[1];
  const numYear = Number(year);
  const numMonth = Number(month);

  if (isNaN(numYear) || isNaN(numMonth) || numYear > 2030 || numYear < 2021 || numMonth < 1 || numMonth > 12) {
    return (
      <Fragment>
        <ErrorAlert>
          <h1 className="text-3xl center text-white">Invalid Filters! Please adjust your values.</h1>
        </ErrorAlert>
        <div className="center my-4">
          <Button link="/events">Show All Events</Button>
        </div>
      </Fragment>
    );
  }

  const filteredEvents = getFilteredEvents({ year: numYear, month: numMonth });

  if (!filteredEvents || filteredEvents.length === 0) {
    return (
      <Fragment>
        <ErrorAlert>
          <h1 className="text-3xl center text-white">No events found for the selected filters.</h1>
        </ErrorAlert>
        <div className="center my-4">
          <Button link="/events">Show All Events</Button>
        </div>
      </Fragment>
    );
  }

  const date = new Date(numYear, numMonth - 1);

  return (
    <Fragment>
      <Head>
        <title>Filtered Events</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ResultsTitle date={date} />
      <section>
        <EventList items={filteredEvents} />
      </section>
    </Fragment>
  );
};

export default FilteredEventsPage;
