import Head from "next/head";
import { useRouter } from "next/router";
import { Fragment } from "react";
import EventContent from "../../components/event-detail/EventContent";
import EventLogistics from "../../components/event-detail/EventLogistics";
import EventSummary from "../../components/event-detail/EventSummary";
import Button from "../../components/ui/Button";
import ErrorAlert from "../../components/ui/ErrorAlert";

import { getEventById } from '../../utils/dummy-data';

const EventDetailPage = () => {
  const router = useRouter();
  const id = router.query.eventId;
  const event = getEventById(id);

  if (!event) {
    return (
      <Fragment>
        <ErrorAlert>
          <h1 className="text-3xl center text-white">No such event found!</h1>
        </ErrorAlert>
        <div className="center my-4">
          <Button link="/events">Show All Events</Button>
        </div>
      </Fragment>
    );
  }

  return (
    <Fragment>
      <Head>
        <title>Dynamic Events Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <EventSummary title={event.title} />
        <EventLogistics
          date={event.date}
          address={event.location}
          image={event.image}
          imageAlt={event.title} />
        <EventContent>
          <p>{event.description}</p>
        </EventContent>
      </section>
    </Fragment>
  );
};

export default EventDetailPage;
