import Head from 'next/head';
import { Fragment } from 'react';


import { getFeaturedEvents } from '../utils/dummy-data';
import EventList from '../components/events/EventList';

const Home = () => {
  const featuredEvents = getFeaturedEvents();

  return (
    <Fragment>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <h1 className="text-5xl center mt-5">Featured Events</h1>
        <EventList items={featuredEvents} />
      </section>
    </Fragment>
  );
};

export default Home;
